version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-local
    ports:
      - "1522:1521" # Exponer puerto de Oracle
    environment:
      ORACLE_PWD: Ora1234 # Contraseña para el usuario SYSTEM
    volumes:
      - oracle-data:/opt/oracle/oradata # Persistencia de datos
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s SYSTEM/Ora1234@localhost:1521/free"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
